/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Subscription = {
  _id: string;
  _type: 'subscription';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  floorLevel?: 'level-5' | 'level-6' | 'level-7';
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote';
      listItem?: 'bullet';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: 'reference';
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
      _key: string;
    }
>;

export type BlockImage = {
  _type: 'blockImage';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Tour = {
  _id: string;
  _type: 'tour';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  prferredPlan?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'floorPlan';
  };
  scheduleDate?: string;
  message?: string;
};

export type MaintenanceRequest = {
  _id: string;
  _type: 'maintenanceRequest';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  unit?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'unit';
  };
  type?:
    | 'plumbing'
    | 'electrical'
    | 'hvac'
    | 'appliances'
    | 'structural'
    | 'pest-control'
    | 'water'
    | 'safety'
    | 'other';
  desc?: string;
};

export type Application = {
  _id: string;
  _type: 'application';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  preferredPlan?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'floorPlan';
  };
  moveIn?: string;
  employmentInfo?: string;
};

export type Term = {
  _id: string;
  _type: 'term';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  desc?: BlockContent;
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  socialLink?: string;
  desc?: string;
  mainImage?: BlockImage;
};

export type Neighborhood = {
  _id: string;
  _type: 'neighborhood';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  socialLink?: string;
  mainImage?: BlockImage;
  type?:
    | 'fitness'
    | 'cafe'
    | 'grocery'
    | 'restaurant'
    | 'park'
    | 'metro-station'
    | 'shopping'
    | 'clinic'
    | 'school'
    | 'community-center';
  minsWalk?: number;
};

export type Amenity = {
  _id: string;
  _type: 'amenity';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  floor?: string;
  subtitle?: string;
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type Blog = {
  _id: string;
  _type: 'blog';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  category?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'category';
  };
  publishedAt?: string;
  mainImage?: BlockImage;
  desc?: BlockContent;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Gallery = {
  _id: string;
  _type: 'gallery';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  mainImages?: Array<
    {
      _key: string;
    } & BlockImage
  >;
};

export type Contact = {
  _id: string;
  _type: 'contact';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  email?: string;
  phone?: string;
  message?: string;
};

export type Unit = {
  _id: string;
  _type: 'unit';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  unitNumber?: string;
  slug?: Slug;
  floorPlan?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'floorPlan';
  };
  isTaken?: boolean;
};

export type FloorPlan = {
  _id: string;
  _type: 'floorPlan';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  subtitle?: string;
  rent?: number;
  bed?: number;
  bath?: number;
  sqFt?: string;
  mainImage?: BlockImage;
  desc?: BlockContent;
  availableRooms?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'unit';
  }>;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Subscription
  | Service
  | BlockContent
  | BlockImage
  | Slug
  | Tour
  | MaintenanceRequest
  | Application
  | Term
  | TeamMember
  | Neighborhood
  | Amenity
  | Blog
  | Category
  | Gallery
  | Contact
  | Unit
  | FloorPlan
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: sanity/lib/queries.ts
// Variable: ALL_FLOOR_PLANS_QUERY
// Query: *[_type == 'floorPlan' && defined(slug.current)]{  name,  slug,  subtitle,  'availableRooms': count(*[_type == 'unit' &&                           references(^._id)] ),  bath,  bed,  sqFt,  rent,  mainImage{    alt,    asset->{url}  }, }
export type ALL_FLOOR_PLANS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  subtitle: string | null;
  availableRooms: number;
  bath: number | null;
  bed: number | null;
  sqFt: string | null;
  rent: number | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: FLOOR_PLAN_QUERY
// Query: *[_type == 'floorPlan' && slug.current == $slug][0]{  name,  slug,  subtitle,  bath,  bed,  sqFt,  rent,  mainImage{    alt,    asset->{url}  },  desc, }
export type FLOOR_PLAN_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  subtitle: string | null;
  bath: number | null;
  bed: number | null;
  sqFt: string | null;
  rent: number | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  desc: BlockContent | null;
} | null;
// Variable: ALL_UNITS_QUERY
// Query: *[_type == 'unit' && defined(slug.current)]{  unitNumber,  slug,  floorPlan->{    name,    rent,    sqFt,    bed,    bath  },  'available': isTaken != true }
export type ALL_UNITS_QUERYResult = Array<{
  unitNumber: string | null;
  slug: Slug | null;
  floorPlan: {
    name: string | null;
    rent: number | null;
    sqFt: string | null;
    bed: number | null;
    bath: number | null;
  } | null;
  available: boolean | true;
}>;
// Variable: ALL_GALLERY_QUERY
// Query: *[_type == 'gallery' && defined(slug.current)]{  name,  slug,  mainImages[]{    alt,    asset->{url}  } }
export type ALL_GALLERY_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  mainImages: Array<{
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  }> | null;
}>;
// Variable: ALL_BLOGS_QUERY
// Query: *[_type == 'blog' && defined(slug.current)]{  title,  slug,  category->{    name  },  publishedAt,  mainImage{    asset->{url},    alt  } }
export type ALL_BLOGS_QUERYResult = Array<{
  title: string | null;
  slug: Slug | null;
  category: {
    name: string | null;
  } | null;
  publishedAt: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
}>;
// Variable: BLOG_QUERY
// Query: *[_type == 'blog' && slug.current == $slug][0]{  title,  slug,  category->{    name  },  publishedAt,  mainImage{    asset->{url},    alt  },  desc }
export type BLOG_QUERYResult = {
  title: string | null;
  slug: Slug | null;
  category: {
    name: string | null;
  } | null;
  publishedAt: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  desc: BlockContent | null;
} | null;
// Variable: ALL_AMENITIES_QUERY
// Query: *[_type == 'amenity' && defined(slug.current)]{  name,  slug,  floor,  subtitle,  mainImage{    asset->{url},    alt  }, }
export type ALL_AMENITIES_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  floor: string | null;
  subtitle: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
}>;
// Variable: AMENITY_QUERY
// Query: *[_type == 'amenity' && slug.current == $slug][0]{  name,  slug,  floor,  subtitle,  mainImage{    asset->{url},    alt  },  desc }
export type AMENITY_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  floor: string | null;
  subtitle: string | null;
  mainImage: {
    asset: {
      url: string | null;
    } | null;
    alt: string | null;
  } | null;
  desc: BlockContent | null;
} | null;
// Variable: ALL_NEIGHBORHOOD_QUERY
// Query: *[_type == 'neighborhood' && defined(slug.current)]{  name,  slug,  socialLink,  mainImage{    alt,    asset->{url}  },  type,  minsWalk }
export type ALL_NEIGHBORHOOD_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  socialLink: string | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
  type:
    | 'cafe'
    | 'clinic'
    | 'community-center'
    | 'fitness'
    | 'grocery'
    | 'metro-station'
    | 'park'
    | 'restaurant'
    | 'school'
    | 'shopping'
    | null;
  minsWalk: number | null;
}>;
// Variable: ALL_TEAM_MEMBERS_QUERY
// Query: *[_type == 'teamMember' && defined(slug.current)]{  name,  slug,  role,  desc,  socialLink }
export type ALL_TEAM_MEMBERS_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  role: string | null;
  desc: string | null;
  socialLink: string | null;
}>;
// Variable: ALL_SERVICES_QUERY
// Query: *[_type == 'service' && defined(slug.current)]{  name,  slug,  price,  floorLevel,  mainImage{    alt,    asset->{url}  }, }
export type ALL_SERVICES_QUERYResult = Array<{
  name: string | null;
  slug: Slug | null;
  price: number | null;
  floorLevel: 'level-5' | 'level-6' | 'level-7' | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
}>;
// Variable: SERVICE_QUERY
// Query: *[_type == 'service' && slug.current == $slug][0]{  name,  slug,  price,  floorLevel,  mainImage{    alt,    asset->{url}  }, }
export type SERVICE_QUERYResult = {
  name: string | null;
  slug: Slug | null;
  price: number | null;
  floorLevel: 'level-5' | 'level-6' | 'level-7' | null;
  mainImage: {
    alt: string | null;
    asset: {
      url: string | null;
    } | null;
  } | null;
} | null;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    "*[_type == 'floorPlan'\n && defined(slug.current)]{\n  name,\n  slug,\n  subtitle,\n  'availableRooms': count(*[_type == 'unit' &&\n                           references(^._id)] ),\n  bath,\n  bed,\n  sqFt,\n  rent,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n }": ALL_FLOOR_PLANS_QUERYResult;
    "\n    *[_type == 'floorPlan'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  subtitle,\n  bath,\n  bed,\n  sqFt,\n  rent,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  desc,\n }": FLOOR_PLAN_QUERYResult;
    "*[_type == 'unit' &&\n defined(slug.current)]{\n  unitNumber,\n  slug,\n  floorPlan->{\n    name,\n    rent,\n    sqFt,\n    bed,\n    bath\n  },\n  'available': isTaken != true\n }": ALL_UNITS_QUERYResult;
    "*[_type == 'gallery'\n && defined(slug.current)]{\n  name,\n  slug,\n  mainImages[]{\n    alt,\n    asset->{url}\n  }\n }": ALL_GALLERY_QUERYResult;
    "*[_type == 'blog'\n && defined(slug.current)]{\n  title,\n  slug,\n  category->{\n    name\n  },\n  publishedAt,\n  mainImage{\n    asset->{url},\n    alt\n  }\n }": ALL_BLOGS_QUERYResult;
    "*[_type == 'blog'\n && slug.current == $slug][0]{\n  title,\n  slug,\n  category->{\n    name\n  },\n  publishedAt,\n  mainImage{\n    asset->{url},\n    alt\n  },\n  desc\n }": BLOG_QUERYResult;
    "*[_type == 'amenity'\n && defined(slug.current)]{\n  name,\n  slug,\n  floor,\n  subtitle,\n  mainImage{\n    asset->{url},\n    alt\n  },\n }": ALL_AMENITIES_QUERYResult;
    "\n    *[_type == 'amenity'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  floor,\n  subtitle,\n  mainImage{\n    asset->{url},\n    alt\n  },\n  desc\n }": AMENITY_QUERYResult;
    "*[_type == 'neighborhood'\n && defined(slug.current)]{\n  name,\n  slug,\n  socialLink,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n  type,\n  minsWalk\n }": ALL_NEIGHBORHOOD_QUERYResult;
    "*[_type == 'teamMember'\n && defined(slug.current)]{\n  name,\n  slug,\n  role,\n  desc,\n  socialLink\n }": ALL_TEAM_MEMBERS_QUERYResult;
    "*[_type == 'service'\n && defined(slug.current)]{\n  name,\n  slug,\n  price,\n  floorLevel,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n }": ALL_SERVICES_QUERYResult;
    "*[_type == 'service'\n && slug.current == $slug][0]{\n  name,\n  slug,\n  price,\n  floorLevel,\n  mainImage{\n    alt,\n    asset->{url}\n  },\n }": SERVICE_QUERYResult;
  }
}
